name: React App Deploy

on:
  push:
    branches:
      - "master"
     # Triggers the workflow on push event only for the master branch

jobs:
  build:
    runs-on: ubuntu-latest #This line refers to the system that runs the action
    concurrency: ci-${{ github.ref }}

    strategy:
      matrix:
        node-version: [15.x] #Here we set the node version to 15.x
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2 #This is a special action provided by github to make a checkout of the v1 

      - name: Install and build
        run: |
          npm ci
          npm install
          npm run build
         #Here we run our scripts
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1 #This is a marketplace action to publish pages to github.io
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: build # The folder the action should deploy.        
